<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Instructions Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines are used for creating instruction
    | messages that we need to display to the user. You are free to modify
    | these language lines according to your application's requirements.
    |
    */

    'label' => 'Instruction',
    'profile_add' => 'Click add item to start profiling. Local property number can be auto-generated by leaving the field as blank. After adding all the items you want to profile, click profile button to start profiling the list of items.',
];
